#!/usr/bin/env python3
"""delta_report.py — turn drift_events.jsonl + corpus_state.json into a signed human-readable delta report.

Register-compliant wording: instruments are *watched*, drift means "evidence citing provision X needs review".
When there is no drift the report says exactly that, with the baseline date — never "compliant" / "certified".

Usage:
  python scripts/delta_report.py [--events drift_events.jsonl] [--state corpus_state.json]
                                 [--outdir reports] [--key PATH_TO_ED25519_PEM]
Signing is optional (omit --key in CI); a signed report carries alg/pub/sig over the canonical manifest,
same scheme as airbench_full.py.
"""
import argparse, base64, datetime as dt, hashlib, json, os, sys


def canonical(o):
    if o is None: return "null"
    if isinstance(o, bool): return "true" if o else "false"
    if isinstance(o, (int, float)): return json.dumps(o)
    if isinstance(o, str): return json.dumps(o, ensure_ascii=False)
    if isinstance(o, list): return "[" + ",".join(canonical(x) for x in o) + "]"
    if isinstance(o, dict):
        return "{" + ",".join(f"{json.dumps(k)}:{canonical(v)}" for k, v in sorted(o.items())) + "}"
    raise TypeError


def load_events(path):
    if not os.path.exists(path):
        return []
    out = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out


def render_markdown(manifest):
    d = manifest["date"]
    ev = manifest["events"]
    lines = [
        f"# Corpus delta report — {d}",
        "",
        f"- Normaliser: `{manifest['normaliser']}`",
        f"- Provisions under watch: **{manifest['provisions_watched']}** "
        f"across {len(manifest['instruments'])} instrument(s): {', '.join(sorted(manifest['instruments']))}",
        f"- Drift events this window: **{len(ev)}**",
        "",
    ]
    if ev:
        lines += ["## Drift detected", ""]
        for e in ev:
            lines.append(
                f"- **{e.get('instrument')} {e.get('provision')}** changed "
                f"({e.get('ts', 'unknown ts')}) — evidence citing this provision needs review. "
                f"hash `{str(e.get('hash_before'))[:12]}…` → `{str(e.get('hash_after'))[:12]}…`"
            )
        lines.append("")
        lines.append("Drift is a change signal, not a compliance verdict. UNMEASURED ≠ fail.")
    else:
        lines += [
            "## No drift",
            "",
            f"No provision text has changed against the recorded baseline as of {d}. "
            "This is an absence-of-change statement over the watched corpus only.",
        ]
    lines += [
        "",
        "---",
        "_Generated by corpus-watch delta_report.py. Signature block in the companion `.sig.json` "
        "covers the canonical manifest (Ed25519, CSOAI issuer key)._",
    ]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--events", default="drift_events.jsonl")
    ap.add_argument("--state", default="corpus_state.json")
    ap.add_argument("--outdir", default="reports")
    ap.add_argument("--key", default=os.environ.get("CORPUS_SIGN_KEY", ""))
    a = ap.parse_args()

    state = json.load(open(a.state)) if os.path.exists(a.state) else {"normaliser": "unknown", "hashes": {}}
    events = load_events(a.events)
    today = dt.date.today().isoformat()

    manifest = {
        "date": today,
        "normaliser": state.get("normaliser", "unknown"),
        "provisions_watched": len(state.get("hashes", {})),
        "instruments": sorted({k.split("::")[0] for k in state.get("hashes", {})}),
        "events": events,
    }
    md = render_markdown(manifest)

    os.makedirs(a.outdir, exist_ok=True)
    md_path = os.path.join(a.outdir, f"delta-{today}.md")
    with open(md_path, "w") as f:
        f.write(md)

    sig_doc = {"report": f"delta-{today}.md", "report_sha256": hashlib.sha256(md.encode()).hexdigest(),
               "manifest": manifest}
    if a.key:
        from cryptography.hazmat.primitives import serialization
        priv = serialization.load_pem_private_key(open(a.key, "rb").read(), password=None)
        payload = canonical(sig_doc).encode()
        sig_doc["alg"] = "Ed25519"
        sig_doc["pub"] = priv.public_key().public_bytes(
            serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo).hex()
        sig_doc["sig"] = base64.b64encode(priv.sign(payload)).decode()
    else:
        sig_doc["alg"] = "unsigned"
    sig_path = os.path.join(a.outdir, f"delta-{today}.sig.json")
    with open(sig_path, "w") as f:
        json.dump(sig_doc, f, indent=2, ensure_ascii=False)

    print(json.dumps({"report": md_path, "sig": sig_path, "events": len(events),
                      "watched": manifest["provisions_watched"], "signed": bool(a.key)}))


if __name__ == "__main__":
    main()
